# Generated by Django 2.1 on 2019-04-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepsis',
            name='data',
            field=models.CharField(default="Enter Patient's data in format like- glucose,Hemoglobin,capillary_ph,color_score", max_length=100),
        ),
    ]
