# Generated by Django 2.1 on 2019-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20190407_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepsis',
            name='data',
            field=models.CharField(default="Enter Patient's data in format - glucose,Hemoglobin,capillary_ph,color_score or upload it in file format", max_length=100),
        ),
    ]
